package GUI;


import wikiviewer.dbHandling;

/**
 * Η κλάση MainGui είναι το κεντρικό παράθυρο της εφαρμογής WikiViewer.
 * Λειτουργεί ως πίνακας ελέγχου (Dashboard) από όπου ο χρήστης μπορεί να έχει πρόσβαση
 * στην αναζήτηση, στα αποθηκευμένα άρθρα και στα στατιστικά στοιχεία.
 * @author PLH24Team Vasiliadou - Aggelopoulos - Kosmidis
 */
public class MainGui extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(MainGui.class.getName());

    /**
     * Κατασκευαστής της κλάσης MainGui.
     * Αρχικοποιεί τα συστατικά της φόρμας, κεντράρει το παράθυρο και 
     * εκκινεί τη διαδικασία ελέγχου/δημιουργίας της βάσης δεδομένων μέσω της {@link dbHandling#buildDB()}.
     */
    public MainGui() {
        initComponents();
        setLocationRelativeTo(null); // Τοποθέτηση στο κέντρο της οθόνης
        
        // Αρχικοποίηση της βάσης δεδομένων κατά την εκκίνηση
        dbHandling.buildDB(); 
    }
    
    /**
     * Βοηθητική μέθοδος για το άνοιγμα ενός νέου παραθύρου.
     * Ρυθμίζει το νέο παράθυρο να εμφανίζεται στο κέντρο σε σχέση με το κύριο μενού.
     * @param w Το αντικείμενο JFrame (παράθυρο) που πρόκειται να προβληθεί.
     */
    private void openWindow(javax.swing.JFrame w) {
        w.setLocationRelativeTo(this);
        w.setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        btnSearchApi = new javax.swing.JButton();
        btnUpdateArticle = new javax.swing.JButton();
        btnSavedArticles = new javax.swing.JButton();
        btnStats = new javax.swing.JButton();
        btnAddCategory = new javax.swing.JButton();
        btnExit = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("WikiViewer");

        btnSearchApi.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnSearchApi.setText("<html>Αναζήτηση άρθρου</html>");
        btnSearchApi.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnSearchApi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchApiActionPerformed(evt);
            }
        });

        btnUpdateArticle.setText("Ενημέρωση Άρθρου");
        btnUpdateArticle.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnUpdateArticle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateArticleActionPerformed(evt);
            }
        });

        btnSavedArticles.setText("Αποθηκευμένα Άρθρα");
        btnSavedArticles.setToolTipText("");
        btnSavedArticles.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnSavedArticles.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSavedArticlesActionPerformed(evt);
            }
        });

        btnStats.setText("Προβολή Στατιστικών");
        btnStats.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnStats.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnStatsActionPerformed(evt);
            }
        });

        btnAddCategory.setText("<html>Προσθήκη<br>\nΚατηγορίας</html>");
        btnAddCategory.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnAddCategory.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddCategoryActionPerformed(evt);
            }
        });

        btnExit.setBackground(new java.awt.Color(255, 0, 204));
        btnExit.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnExit.setText("Έξοδος");
        btnExit.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExitActionPerformed(evt);
            }
        });

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/WIKI.png"))); // NOI18N
        jLabel2.setText("jLabel2");

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 0, 204));
        jLabel1.setText("ΠΛΗ 24");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 8)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 0, 204));
        jLabel3.setText("2025-2026");

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 10)); // NOI18N
        jLabel10.setText("<html>Product owner:<br>Scrum Team:<br>Scrum Master:</html>");
        jLabel10.setToolTipText("");

        jLabel11.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        jLabel11.setText("<html>Ευθύμιος Αλέπης<br>Scrum Team:Παύλος Κοσμίδης - Δημοσθένης Αγγελόπουλος - Νικολέτα Βασιλειάδου<br>Παύλος Κοσμίδης:</html>");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(75, 75, 75)
                        .addComponent(jLabel3))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 863, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(39, 39, 39)
                                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(79, 79, 79)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnSearchApi, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnUpdateArticle, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnSavedArticles, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnStats, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnAddCategory, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnExit, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btnSearchApi, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnUpdateArticle, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnSavedArticles, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnStats, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnAddCategory, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnExit, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 395, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addGap(0, 8, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Διαχειρίζεται το πάτημα του κουμπιού "Αναζήτηση άρθρου".
     * Ανοίγει το παράθυρο {@link SearchWiki}.
     * @param evt Το συμβάν ενέργειας.
     */
    private void btnSearchApiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchApiActionPerformed
        openWindow(new SearchWiki());
    }//GEN-LAST:event_btnSearchApiActionPerformed
    
    /**
     * Διαχειρίζεται το πάτημα του κουμπιού "Ενημέρωση Άρθρου".
     * @param evt Το συμβάν ενέργειας.
     */
    private void btnUpdateArticleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateArticleActionPerformed
    // Μελλοντική υλοποίηση
    }//GEN-LAST:event_btnUpdateArticleActionPerformed

    /**
     * Διαχειρίζεται το πάτημα του κουμπιού "Αποθηκευμένα Άρθρα".
     * Ανοίγει το παράθυρο {@link SavedArticles}.
     * @param evt Το συμβάν ενέργειας.
     */
    private void btnSavedArticlesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSavedArticlesActionPerformed
        openWindow(new SavedArticles());
    }//GEN-LAST:event_btnSavedArticlesActionPerformed

    /**
     * Διαχειρίζεται το πάτημα του κουμπιού "Προβολή Στατιστικών".
     * Ανοίγει το παράθυρο {@link Statistics}.
     * @param evt Το συμβάν ενέργειας.
     */
    private void btnStatsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnStatsActionPerformed
        openWindow(new Statistics());
    }//GEN-LAST:event_btnStatsActionPerformed

    /**
     * Διαχειρίζεται το πάτημα του κουμπιού "Προσθήκη Κατηγορίας".
     * @param evt Το συμβάν ενέργειας.
     */
    private void btnAddCategoryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddCategoryActionPerformed
    // Μελλοντική υλοποίηση
    }//GEN-LAST:event_btnAddCategoryActionPerformed

    /**
     * Διαχειρίζεται την έξοδο από την εφαρμογή.
     * Εμφανίζει ένα παράθυρο επιβεβαίωσης στον χρήστη πριν τον τερματισμό.
     * @param evt Το συμβάν ενέργειας.
     */
    private void btnExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExitActionPerformed
       int ans = javax.swing.JOptionPane.showConfirmDialog(
        this,
        "Θέλεις να κλείσεις την εφαρμογή;",
        "Έξοδος",
        javax.swing.JOptionPane.YES_NO_OPTION
    );
    if (ans == javax.swing.JOptionPane.YES_OPTION) {
        System.exit(0); 
    }
    }//GEN-LAST:event_btnExitActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddCategory;
    private javax.swing.JButton btnExit;
    private javax.swing.JButton btnSavedArticles;
    private javax.swing.JButton btnSearchApi;
    private javax.swing.JButton btnStats;
    private javax.swing.JButton btnUpdateArticle;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    // End of variables declaration//GEN-END:variables
}
