package GUI;
import model.Article;

import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;
import api.GetResults;
import db.dbHandling;
import java.net.URL;
import java.net.URLConnection;
import java.util.List;
import javax.swing.SwingWorker;

/**
 * Η κλάση SearchWiki αποτελεί το κεντρικό παράθυρο αναζήτησης της εφαρμογής.
 * Παρέχει μια διεπαφή χρήστη (GUI) που επιτρέπει την αναζήτηση άρθρων στη 
 * Wikipedia, την προβολή των αποτελεσμάτων σε λίστα και την αποθήκευση των 
 * λέξεων-κλειδιών στη βάση.
 * @author PLH24Team Vasiliadou - Aggelopoulos - Kosmidis
 */
public class SearchWiki extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = 
            java.util.logging.Logger.getLogger(SearchWiki.class.getName());

    /**
     * Κατασκευαστής της κλάσης. 
     * Αρχικοποιεί τα συστατικά του GUI και ορίζει το μοντέλο δεδομένων 
     * για τη λίστα αποτελεσμάτων.
     */
    public SearchWiki() {
        initComponents();
        // Ορισμός κενού μοντέλου στη jList2 για τη δυναμική προσθήκη 
        //αντικειμένων Article
        jList2.setModel(new DefaultListModel<>());
        jProgressBar1.setVisible(false);
        jProgressBar1.setStringPainted(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jList2 = new javax.swing.JList<>();
        jButtonOpen = new javax.swing.JButton();
        jButtonExit = new javax.swing.JButton();
        jButtonSave = new javax.swing.JButton();
        jProgressBar1 = new javax.swing.JProgressBar();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Search Wiki");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/WikiViewerLabel.png"))); // NOI18N

        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });
        jTextField1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextField1KeyTyped(evt);
            }
        });

        jButton1.setText("Αναζήτηση");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jList2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jList2MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jList2);

        jButtonOpen.setText("Άνοιγμα");
        jButtonOpen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonOpenActionPerformed(evt);
            }
        });

        jButtonExit.setText("Έξοδος");
        jButtonExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonExitActionPerformed(evt);
            }
        });

        jButtonSave.setText("Αποθήκευση");
        jButtonSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSaveActionPerformed(evt);
            }
        });

        jProgressBar1.setToolTipText("");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(115, 115, 115)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jProgressBar1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jScrollPane1)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 485, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jButton1))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addComponent(jButtonSave)
                            .addGap(35, 35, 35)
                            .addComponent(jButtonOpen)
                            .addGap(33, 33, 33)
                            .addComponent(jButtonExit))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jProgressBar1, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 224, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonOpen)
                    .addComponent(jButtonExit)
                    .addComponent(jButtonSave))
                .addGap(0, 35, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
 
    /**
     * Διαχειρίζεται το πάτημα του κουμπιού "Αναζήτηση".
     * Ελέγχει αν υπάρχει σύνδεση στο Internet και αν ναι 
     * ανακτά τα άρθρα μέσω του {@link GetResults#getList}, ενημερώνει 
     * τη λίστα στο GUI και αποθηκεύει τη λέξη-κλειδί στη βάση δεδομένων.
     * @param evt Το συμβάν ενέργειας (action event).
     */
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        
        if (hasInternetConnection()== true)
        {
            
            String searchText = jTextField1.getText();
            if (searchText.isEmpty()) 
            {
                javax.swing.JOptionPane.showMessageDialog(this, "Παρακαλώ πληκτρολογήστε κάτι!");
                return;
            }
            jProgressBar1.setVisible(true);
            jProgressBar1.setIndeterminate(true);
            jProgressBar1.setString("Φόρτωση...");
            jButton1.setEnabled(false);
            jButtonOpen.setEnabled(false);
            jButtonSave.setEnabled(false);
            
            SwingWorker<Article[], Void> worker = new SwingWorker<>()
            {
                @Override
                protected  Article[] doInBackground() throws Exception
                {                   
                    return GetResults.getList(searchText);
                }
                
                @Override
                protected void done()
                {
                    try
                    {
                        Article[] articles = get();
                        // Ενημερώνουμε τη λίστα
                        DefaultListModel<Article> model = 
                          (DefaultListModel<Article>) jList2.getModel();
                        
                        model.clear();
                        for (Article a: articles)
                        {
                            model.addElement(a);
                        }
                         
                    }catch (Exception e)
                    {
                    javax.swing.JOptionPane.showMessageDialog(null, "Σφάλμα "
                            + "κατά την αναζήτηση.");
                    }finally
                    {
                        jProgressBar1.setIndeterminate(false);
                        jProgressBar1.setVisible(false);
                        jButton1.setEnabled(true);
                        jButtonOpen.setEnabled(true);
                        jButtonSave.setEnabled(true);
                    }
                }
                    
            };
            worker.execute();
        }else
        {
            javax.swing.JOptionPane.showMessageDialog(this, 
            "Δεν υπάρχει σύνδεση στο Διαδίκτυο!\nΕλέγξτε το δίκτυό σας και προσπαθήστε ξανά.", 
            "Σφάλμα Σύνδεσης", 
            javax.swing.JOptionPane.ERROR_MESSAGE);
        }
        
        
        
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * Κλείνει το τρέχον παράθυρο αναζήτησης.
     * @param evt Το συμβάν ενέργειας.
     */
    private void jButtonExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonExitActionPerformed
        this.dispose();
    }//GEN-LAST:event_jButtonExitActionPerformed

    private void jTextField1KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField1KeyTyped
        
    }//GEN-LAST:event_jTextField1KeyTyped

    /**
    * Επιτρέπει την εκτέλεση αναζήτησης με το πάτημα του "Enter" 
    * μέσα στο πεδίο κειμένου.
    * @param evt Το συμβάν ενέργειας.
    */  
    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        jButton1ActionPerformed(evt);
    }//GEN-LAST:event_jTextField1ActionPerformed

    /**
     * Διαχειρίζεται το πάτημα του κουμπιού "Άνοιγμα".
     * Λαμβάνει το επιλεγμένο άρθρο από τη λίστα και ανοίγει το 
     * παράθυρο λεπτομερειών.
     * Ελέγχει αν το άρθρο υπάρχει ήδη στη βάση δεδομένων για να φορτώσει 
     * τυχόν αποθηκευμένα σχόλια/βαθμολογία.
     * @param evt Το συμβάν ενέργειας.
     */
    private void jButtonOpenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonOpenActionPerformed
        if (jList2.getSelectedValue() != null)
        {
            Article selectedArticle = (Article) jList2.getSelectedValue();
            // Έλεγχος αν το άρθρο είναι ήδη αποθηκευμένο στη βάση
            Article art = dbHandling.getArticleByTitle(selectedArticle.getTitle());
                        
            if(art.getTitle()!= null)
            {
                // Αν υπάρχει στη βάση, ανοίγουμε το παράθυρο με τα 
                //δεδομένα της βάσης
                openWindow(new ArticleView(art));               
            }
            else
            {
                // Αν δεν υπάρχει, ανοίγουμε το παράθυρο με τα δεδομένα από το API
                openWindow(new ArticleView(selectedArticle));
            }           
             
        }
        
    }//GEN-LAST:event_jButtonOpenActionPerformed

    /**
     * Μεταφέρει τον κέρσορα κατα το άνοιγμα του παραθύρου στο Search
     * @param evt Το άνοιγμα του παραθύρου.
     */
    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        jTextField1.requestFocusInWindow();
    }//GEN-LAST:event_formWindowOpened

    /**
     * Επιτρέπει το άνοιγμα ενός άρθρου με διπλό κλικ πάνω στη λίστα.
     * @param evt Το συμβάν ποντικιού.
     */
    private void jList2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jList2MouseClicked
        if (evt.getClickCount() == 2) {
            jButtonOpen.doClick();
        }
    }//GEN-LAST:event_jList2MouseClicked
    
     /**
     * Διαχειρίζεται το πάτημα του κουμπιού "Αποθήκευση".
     * Δημιουργεί ένα αντικείμενο Article και κάνει Εισαγωγή 
     * (insert) στη βάση δεδομένων.
     * @param evt Το συμβάν ενέργειας του κουμπιού.
     */
    private void jButtonSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSaveActionPerformed
        
        // Αν υπάρχει επιλεγμένο, Insert
        if (jList2.getSelectedIndex() != -1) 
        {
            Article art = jList2.getSelectedValue();
            art.setCategory(dbHandling.getAllCategory().getFirst());
            
            if (dbHandling.getArticleByTitle(art.getTitle()).getTitle()== null)
            {
                if (dbHandling.insertArticle(art)) {
                    JOptionPane.showMessageDialog(this, "Η αποθήκευση έγινε "
                            + "με επιτυχία!");
                } else {
                    JOptionPane.showMessageDialog(this, "Η αποθήκευση απέτυχε!");
                }
            }else
            {
                JOptionPane.showMessageDialog(this, "Το άρθρο έχει ήδη αποθηκευτεί.");
            }
            

        }
        
    }//GEN-LAST:event_jButtonSaveActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButtonExit;
    private javax.swing.JButton jButtonOpen;
    private javax.swing.JButton jButtonSave;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JList<Article> jList2;
    private javax.swing.JProgressBar jProgressBar1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
    
    /**
    * Βοηθητική μέθοδος για το άνοιγμα ενός νέου παραθύρου.
    * Τοποθετεί το νέο παράθυρο στο κέντρο σε σχέση με το παρόν.
    * @param w Το αντικείμενο JFrame που πρόκειται να εμφανιστεί.
    */
    private void openWindow(javax.swing.JFrame w) 
    {
        w.setLocationRelativeTo(this);
        w.setVisible(true);
    }
    
    /**
    * Βοηθητική μέθοδος για τον έλεγχο της σύνδεσης στο Intenet.
    * @return true αν υπάρχει δύνδεση, false άν όχι.
    */
    private boolean hasInternetConnection()
    {
        try 
        {
            URL url = new URL("http://www.google.com");
            URLConnection connection = url.openConnection();
            
            connection.setConnectTimeout(3000);
            connection.connect();
            
            return true;
        } catch (Exception e) {
            return false;
        }
    }

}
