package GUI;

import java.awt.HeadlessException;
import java.util.List;
import javax.swing.JButton;
import javax.swing.JPanel;
import javax.swing.JScrollPane;
import javax.swing.JTabbedPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
import db.dbHandling;
import com.lowagie.text.Document;
import com.lowagie.text.DocumentException;
import com.lowagie.text.Font;
import com.lowagie.text.Paragraph;
import com.lowagie.text.pdf.BaseFont;
import com.lowagie.text.pdf.PdfPTable;
import com.lowagie.text.pdf.PdfWriter;
import java.io.FileOutputStream;
import java.io.IOException;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import com.lowagie.text.pdf.PdfPCell;
import com.lowagie.text.Element;
import com.lowagie.text.Phrase;
import java.awt.BorderLayout;
import org.jfree.chart.ChartFactory;
import org.jfree.chart.ChartPanel;
import org.jfree.chart.JFreeChart;
import org.jfree.data.general.DefaultPieDataset;
import javax.swing.JDialog;
import java.awt.Color;
import java.awt.Graphics;
import model.Statistic;

/**
 * Η κλάση Stristics αποτελεί το παράθυρο εμφάνισης στατιστικών της εφαρμογής.
 * Περιλαμβάνει δύο βασικές καρτέλες (Tabs): 
 * 1) Καταμέτρηση λέξεων-κλειδιών αναζήτησης.
 * 2) Καταμέτρηση αποθηκευμένων άρθρων ανά κατηγορία.
 * Παρέχει δυνατότητα οπτικοποίησης μέσω Pie Chart και εξαγωγής των δεδομένων σε PDF.
 * * @author PLH24Team Vasiliadou - Aggelopoulos - Kosmidis
 */
public class Statistics extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = 
            java.util.logging.Logger.getLogger(Statistics.class.getName());
    
    /**
     * Κατασκευαστής της κλάσης Stristics.
     * Αρχικοποιεί το GUI, μορφοποιεί τις κεφαλίδες των πινάκων και φορτώνει 
     * τα αρχικά δεδομένα.
     */
    public Statistics() {
        initComponents();
    
        // Μορφοποίηση κεφαλίδων για τον πίνακα Keywords
        javax.swing.table.JTableHeader header = jTableKeywords.getTableHeader();
        header.setFont(new java.awt.Font("Tahoma", java.awt.Font.BOLD, 16));
        header.setForeground(java.awt.Color.LIGHT_GRAY);

        // Μορφοποίηση κεφαλίδων για τον πίνακα Κατηγοριών
        javax.swing.table.JTableHeader header1 = jTablePerCategory.getTableHeader();
        header1.setFont(new java.awt.Font("Tahoma", java.awt.Font.BOLD, 16));
        header1.setForeground(java.awt.Color.LIGHT_GRAY);
        
        // Ανάκτηση δεδομένων από τη βάση και εμφάνιση στους πίνακες
        List<Statistic> statsC = dbHandling.getCategoryStats();
        if (statsC == null)
        {
            JOptionPane.showMessageDialog(Statistics.this, "!!! Πρόβλημα με τη"
                    + "βάση δεδομένων !!!");
        }else{
            showStatsInTable(jTablePerCategory, statsC);
        }
        
        
        List<Statistic> statsK = dbHandling.getKeywordStats();
        if (statsK == null)
        {
            JOptionPane.showMessageDialog(Statistics.this, "!!! Πρόβλημα με τη"
                    + "βάση δεδομένων !!!");
        }else{
            showStatsInTable(jTableKeywords, statsK);
            // Αρχική φόρτωση γραφήματος για τις λέξεις-κλειδιά
            loadChart(statsK, "Δημοφιλείς Λέξεις");
        }
        
        
        
       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableKeywords = new javax.swing.JTable();
        jPanel4 = new javax.swing.JPanel();
        jButtonExit = new javax.swing.JButton();
        jButtonPDF = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTablePerCategory = new javax.swing.JTable();
        jPanel5 = new javax.swing.JPanel();
        jButtonPDF2 = new javax.swing.JButton();
        jButtonExit1 = new javax.swing.JButton();
        panelChartContainer = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jTabbedPane1.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jTabbedPane1StateChanged(evt);
            }
        });
        jTabbedPane1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTabbedPane1FocusGained(evt);
            }
        });
        jTabbedPane1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTabbedPane1MouseClicked(evt);
            }
        });

        jTableKeywords.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jTableKeywords.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Keyword", "Πλήθος"
            }
        ));
        jScrollPane1.setViewportView(jTableKeywords);

        jButtonExit.setText("Έξοδος");
        jButtonExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonExitActionPerformed(evt);
            }
        });

        jButtonPDF.setText("Εξαγωγή PDF");
        jButtonPDF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPDFActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addComponent(jButtonPDF)
                .addGap(0, 12, Short.MAX_VALUE))
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jButtonExit)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButtonPDF)
                .addGap(80, 80, 80)
                .addComponent(jButtonExit)
                .addContainerGap(131, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 575, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(44, Short.MAX_VALUE)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(92, 92, 92))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 333, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jTabbedPane1.addTab("Keywords Count", jPanel1);

        jTablePerCategory.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jTablePerCategory.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Κατηγορία", "Πλήθος Άρθρων"
            }
        ));
        jScrollPane2.setViewportView(jTablePerCategory);

        jButtonPDF2.setText("Εξαγωγή PDF");
        jButtonPDF2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPDF2ActionPerformed(evt);
            }
        });

        jButtonExit1.setText("Έξοδος");
        jButtonExit1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonExit1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                        .addComponent(jButtonPDF2)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                        .addComponent(jButtonExit1)
                        .addGap(29, 29, 29))))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(51, 51, 51)
                .addComponent(jButtonPDF2)
                .addGap(78, 78, 78)
                .addComponent(jButtonExit1)
                .addContainerGap(159, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 569, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(92, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        jTabbedPane1.addTab("Άρθρα ανα Κατηγορία", jPanel3);

        javax.swing.GroupLayout panelChartContainerLayout = new javax.swing.GroupLayout(panelChartContainer);
        panelChartContainer.setLayout(panelChartContainerLayout);
        panelChartContainerLayout.setHorizontalGroup(
            panelChartContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        panelChartContainerLayout.setVerticalGroup(
            panelChartContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 388, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelChartContainer, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 373, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelChartContainer, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    /**
     * Διαχειρίζεται το πάτημα του κουμπιού "Εξαγωγή PDF" για τα keywords στατιστικά.
     * @param evt Το συμβάν ενέργειας του κουμπιού.
     */
    private void jButtonPDFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPDFActionPerformed
        makePDF(jTableKeywords, "Στατιστικά Λέξεων");
    }//GEN-LAST:event_jButtonPDFActionPerformed

    /**
     * Διαχειρίζεται το πάτημα του κουμπιού "Εξαγωγή PDF" για τα στατιστικά Καταλόγου.
     * @param evt Το συμβάν ενέργειας του κουμπιού.
     */
    private void jButtonPDF2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPDF2ActionPerformed
        makePDF(jTablePerCategory, "Άρθρα ανά Κατηγορία");
    }//GEN-LAST:event_jButtonPDF2ActionPerformed

    /**
     * Κλείνει το παράθυρο των Στατιστικών.
     * @param evt Το συμβάν ενέργειας του κουμπιού.
     */
    private void jButtonExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonExitActionPerformed
        this.dispose();
    }//GEN-LAST:event_jButtonExitActionPerformed

    private void jTabbedPane1FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTabbedPane1FocusGained

    }//GEN-LAST:event_jTabbedPane1FocusGained

    private void jTabbedPane1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTabbedPane1MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jTabbedPane1MouseClicked

    /**
     * Διαχειρίζεται την αλλαγή καρτέλας (Tab) στο JTabbedPane.
     * Ενημερώνει δυναμικά το γράφημα (Chart) ανάλογα με την επιλεγμένη ενότητα.
     * @param evt Το συμβάν αλλαγής κατάστασης.
     */
    private void jTabbedPane1StateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jTabbedPane1StateChanged
        int index = jTabbedPane1.getSelectedIndex();
        if (index == 0)
        {
            List<Statistic> stats = dbHandling.getKeywordStats();           
            loadChart(stats, "Δημοφιλείς Λέξεις");
        }else if (index == 1)
        {
            List<Statistic> stats = dbHandling.getCategoryStats();
            loadChart(stats, "Άρθρα ανά Κατηγορία");
        }
    }//GEN-LAST:event_jTabbedPane1StateChanged

     /**
     * Κλείνει το παράθυρο των Στατιστικών.
     * @param evt Το συμβάν ενέργειας του κουμπιού.
     */
    private void jButtonExit1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonExit1ActionPerformed
        this.dispose();
    }//GEN-LAST:event_jButtonExit1ActionPerformed

    public Statistics(JButton jButtonExit, JButton jButtonExit1, JButton jButtonPDF, JButton jButtonPDF2, JPanel jPanel1, JPanel jPanel2, JPanel jPanel3, JPanel jPanel4, JPanel jPanel5, JPanel jPanel6, JScrollPane jScrollPane1, JScrollPane jScrollPane2, JTabbedPane jTabbedPane1, JTable jTableKeywords, JTable jTableKeywords1) throws HeadlessException {
        this.jButtonExit = jButtonExit;
        this.jButtonExit1 = jButtonExit1;
        this.jButtonPDF = jButtonPDF;
        this.jButtonPDF2 = jButtonPDF2;
        this.jPanel1 = jPanel1;
        this.jPanel2 = jPanel2;
        this.jPanel3 = jPanel3;
        this.jPanel4 = jPanel4;
        this.jPanel5 = jPanel5;
        this.jPanel6 = jPanel6;
        this.jScrollPane1 = jScrollPane1;
        this.jScrollPane2 = jScrollPane2;
        this.jTabbedPane1 = jTabbedPane1;
        this.jTableKeywords = jTableKeywords;
        this.jTablePerCategory = jTableKeywords1;
    }

    @Override
    public void dispose() {
        super.dispose(); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/OverriddenMethodBody
    }

    @Override
    public Graphics getGraphics() {
        return super.getGraphics(); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/OverriddenMethodBody
    }

    /**
     * Γεμίζει έναν JTable με δεδομένα από μια λίστα αντικειμένων Statistic.
     * @param table Ο πίνακας προς ενημέρωση.
     * @param stats Η λίστα με τα στατιστικά δεδομένα.
     */
    private void showStatsInTable(JTable table, List<Statistic> stats ) {
        
        DefaultTableModel model = (DefaultTableModel) table.getModel();

        model.setRowCount(0); // Καθαρισμός πίνακα

        for (Statistic stat : stats) {
            Object[] row = new Object[2];

            row[0] = stat.getName();  // Στήλη 1: Κατηγορία
            row[1] = stat.getCount(); // Στήλη 2: Πλήθος

            model.addRow(row);
        }
    }
    
    /**
     * Δημιουργεί και εμφανίζει ένα 3D κυκλικό διάγραμμα (Pie Chart) 
     * στο panelChartContainer.
     * Χρησιμοποιεί τη βιβλιοθήκη JFreeChart.
     * @param stats Η λίστα δεδομένων προς οπτικοποίηση.
     * @param title Ο τίτλος του γραφήματος.
     */
    public void loadChart(List<Statistic> stats, String title) 
    {
    
        panelChartContainer.removeAll();
        //Για να πιάσει όλο το χώρο
        panelChartContainer.setLayout(new BorderLayout()); 

        DefaultPieDataset dataset = new DefaultPieDataset();
        for (Statistic s : stats) 
        {
            dataset.setValue(s.getName(), s.getCount());
        }

        JFreeChart chart = ChartFactory.createPieChart3D(
                title,
                dataset,
                true, 
                true, 
                false
        );

        ChartPanel chartPanel = new ChartPanel(chart);
        panelChartContainer.add(chartPanel, BorderLayout.CENTER);

        panelChartContainer.validate();
        panelChartContainer.repaint();
    }
    
    /**
     * Εξάγει τα δεδομένα ενός JTable σε αρχείο PDF.
     * Περιλαμβάνει υποστήριξη Ελληνικών χαρακτήρων μέσω εξωτερικής γραμματοσειράς .ttf.
     * @param table Ο πίνακας του οποίου τα δεδομένα θα εξαχθούν.
     * @param docTitle Ο τίτλος που θα αναγράφεται στο έγγραφο PDF.
     */
    public void makePDF(JTable table, String docTitle)
    {
        JFileChooser fileChooser = new JFileChooser();
        fileChooser.setDialogTitle("Αποθήκευση PDF");
        int userSelection = fileChooser.showSaveDialog(this);

        if (userSelection == JFileChooser.APPROVE_OPTION) 
        {
            String filePath = fileChooser.getSelectedFile().getAbsolutePath();
            if (!filePath.endsWith(".pdf")) filePath += ".pdf"; // Προσθήκη κατάληξης

                try {
                    Document document = new Document();
                    PdfWriter.getInstance(document, new FileOutputStream(filePath));
                    document.open();

                    BaseFont bf = BaseFont.createFont("arial.ttf", BaseFont.IDENTITY_H, BaseFont.EMBEDDED);
                    Font titleFont = new Font(bf, 22, Font.BOLD);
                    Font textFont = new Font(bf, 12, Font.NORMAL);

                    Paragraph title = new Paragraph(docTitle, titleFont);
                    title.setAlignment(Element.ALIGN_CENTER); // Κεντράρισμα
                    title.setSpacingAfter(20); // Κενό από κάτω
                    document.add(title);

                    PdfPTable pdfTable = new PdfPTable(table.getColumnCount());
                    pdfTable.setWidthPercentage(100);

                    for (int i = 0; i < table.getColumnCount(); i++) 
                    {
                        String headerText = table.getColumnName(i);
                        PdfPCell cell = new PdfPCell(new Phrase(headerText, textFont));
                        cell.setBackgroundColor(Color.LIGHT_GRAY);
                        cell.setHorizontalAlignment(Element.ALIGN_CENTER);
                        cell.setVerticalAlignment(Element.ALIGN_MIDDLE);
                        cell.setPadding(5);
                        pdfTable.addCell(cell);
                    }

                    for (int rows = 0; rows < table.getRowCount(); rows++) {
                        for (int cols = 0; cols < table.getColumnCount(); cols++) {
                            // Παίρνουμε την τιμή και τη μετατρέπουμε σε String
                            String value = table.getModel().getValueAt(rows, cols).toString();
                            pdfTable.addCell(value);
                        }
                }

                document.add(pdfTable);
                document.close();
                JOptionPane.showMessageDialog(this, "Το PDF αποθηκεύτηκε επιτυχώς!");

            } catch (DocumentException | IOException e) 
            {
                JOptionPane.showMessageDialog(this, "Σφάλμα: " + e.getMessage());
            }
        }   
    }
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonExit;
    private javax.swing.JButton jButtonExit1;
    private javax.swing.JButton jButtonPDF;
    private javax.swing.JButton jButtonPDF2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTable jTableKeywords;
    private javax.swing.JTable jTablePerCategory;
    private javax.swing.JPanel panelChartContainer;
    // End of variables declaration//GEN-END:variables
}
