#C:\Users\p.cosmides\OneDrive - E-Analysis OE\Documents\\u0395\u0391\u03A0\PLH24\3\u03B7 \u0393\u03C1\u03B1\u03C0\u03C4\u03AE \u0395\u03C1\u03B3\u03B1\u03C3\u03AF\u03B1\WikiViewer\wikidbM001
#Tue Feb 03 13:15:27 EET 2026
SyscolumnsIdentifier=144
SyscolumnsIndex1Identifier=161
SyscolumnsIndex2Identifier=177
SysconglomeratesIdentifier=32
SysconglomeratesIndex1Identifier=49
SysconglomeratesIndex2Identifier=65
SysconglomeratesIndex3Identifier=81
SysschemasIdentifier=192
SysschemasIndex1Identifier=209
SysschemasIndex2Identifier=225
SystablesIdentifier=96
SystablesIndex1Identifier=113
SystablesIndex2Identifier=129
derby.serviceLocale=el_GR
derby.serviceProtocol=org.apache.derby.database.Database
derby.storage.propertiesId=16
#--- last line, don't put anything after this line ---
